Repository nathanielmillard/whatsCookinRefactor, pull requests merged in 2020-09, with the labels that each got.

#24 Fetch global data
  src/scripts.js
  src/user.js
Labels: enhancement

#27 Dom object
  src/domUpdates.js
  src/scripts.js
Labels: enhancement

#28 Post requests
  src/domUpdates.js
  src/pantry.js
  src/scripts.js
  src/user.js
Labels: documentation, enhancement

#30 Search bug fix
  src/domUpdates.js
  src/scripts.js
Labels: bug

#32 Sass css styling
  src/css/_mixins.scss
  src/css/_variables.scss
  src/css/base.scss
  src/css/styles.scss
  src/domUpdates.js
  src/index.html
Labels: enhancement

#39 Ingredient bug fix
  src/domUpdates.js
  src/index.html
Labels: bug

#40 Media queries
  src/css/styles.scss
  src/domUpdates.js
  src/index.html
Labels: enhancement
